---
ID: "ece04ca2-2810-4736-afcc-8eed35ee5771"
Parent: "cb8de01d-c0c3-4c19-ada6-6811fda4ea8e"
Template: "cb8de01d-c0c3-4c19-ada6-6811fda4ea8e"
Path: /sitecore/templates/Project/lighthouse/Pages/Article Page/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "0693c6c7-2885-430b-8576-d391c57e3c24"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260413T132751Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\superuser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8bd9d68d-f7ea-4892-8ca0-b8036ef8689b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260416T194736Z
