---
ID: "6da3bb0f-8ce9-4427-850d-eee075bb44bf"
Parent: "a7406351-48a1-4e99-bc93-05a58b7dc08a"
Template: "a7406351-48a1-4e99-bc93-05a58b7dc08a"
Path: "/sitecore/templates/Project/nextjs-article_starter/JSS Settings/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250827T180402Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea06c794-9fad-4038-acb5-4c67d8234b2b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T180402Z
