---
ID: "f16750b3-a143-472c-ac5e-5860d6b20f64"
Parent: "abf56ac8-9bdc-454d-83f1-f2f2cb00c28d"
Template: "abf56ac8-9bdc-454d-83f1-f2f2cb00c28d"
Path: "/sitecore/templates/Project/angular-starter/Page Designs/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {010090A6-EB12-415A-903D-FB883D2CCBB1}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e9940504-9d29-43b6-a961-a883c3fc9945"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250827T175551Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f7ba928b-9fa0-40cc-81ae-e8ddfded2f02"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T175554Z
