---
ID: "9543db6c-cf3b-4cbd-9f00-2421deeca805"
Parent: "dc409e51-112e-4148-bf2a-b9b0e4a4ad41"
Template: "dc409e51-112e-4148-bf2a-b9b0e4a4ad41"
Path: /sitecore/templates/Project/lighthouse/Site/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{FD2059FD-6043-4DFE-8C04-E2437CE87634}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8acb040b-834b-42a3-a8ee-bb9cf4de6690"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260406T153228Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kevin.buckley@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e11d4fc8-3235-4aee-9c55-f03772e7ea80"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260514T163046Z
