/**
 * Generates src/environments/environment.dev.ts or environment.prod.ts
 * from `.env` files (via dotenv). Only variables whose names start with `CSDK_PUBLIC_`
 * are written into the file so the browser bundle does not embed server-only secrets.
 *
 * Server-side code reads full configuration from `process.env` at runtime
 * (see `defineConfig` in `@sitecore-content-sdk/angular` and `load-env.ts` / `server.ts`).
 *
 * Usage:
 *   tsx scripts/generate-environment.ts --dev   (loads .env then .env.dev)
 *   tsx scripts/generate-environment.ts --prod  (loads .env then .env.prod)
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import dotenv from 'dotenv';

const projectRoot = process.cwd();
const angularEnvDir = resolve(projectRoot, 'src', 'environments');

function loadEnvFiles(mode: 'dev' | 'prod'): void {
  const contextEnvFile = mode === 'dev' ? '.env.dev' : '.env.prod';

  const baseEnvPath = resolve(projectRoot, '.env');
  const localEnvPath = resolve(projectRoot, '.env.local');
  const contextEnvPath = resolve(projectRoot, contextEnvFile);
  // override: true so a leftover SITECORE_* / CSDK_PUBLIC_* from the parent
  // shell cannot leak into environment.*.ts (dotenv skips existing keys by default).
  dotenv.config({ path: [baseEnvPath, localEnvPath, contextEnvPath], override: true });
}

function serialize(production: boolean): string {
  const publicEnv: Record<string, string> = {};

  for (const key of Object.keys(process.env)) {
    if (key.startsWith('CSDK_PUBLIC_')) {
      publicEnv[key] = process.env[key] ?? '';
    }
  }

  // XM Cloud - and the Deploy app's Developer settings panel, even with Angular selected -
  // only ever exposes the unprefixed SITECORE_EDGE_CONTEXT_ID, never a CSDK_PUBLIC_* variant,
  // so the filter above can never pick it up on a clean build container. Map it across: the
  // browser needs it as `clientContextId`, and the client context ID is public by design.
  if (!publicEnv.CSDK_PUBLIC_SITECORE_EDGE_CONTEXT_ID && process.env.SITECORE_EDGE_CONTEXT_ID) {
    publicEnv.CSDK_PUBLIC_SITECORE_EDGE_CONTEXT_ID = process.env.SITECORE_EDGE_CONTEXT_ID;
  }

  // Without a context ID the browser bundle gets an empty `clientContextId`, the SDK falls back
  // to a relative '/api/graphql' endpoint, and GraphQLRequestClient throws on it - the app never
  // bootstraps and the page renders blank. Fail the build instead of shipping that.
  if (production && !publicEnv.CSDK_PUBLIC_SITECORE_EDGE_CONTEXT_ID) {
    throw new Error(
      'No Edge context ID resolved for a production build. Set SITECORE_EDGE_CONTEXT_ID or ' +
        'CSDK_PUBLIC_SITECORE_EDGE_CONTEXT_ID in the build environment.'
    );
  }

  const lines: string[] = [`  production: '${production}',`];
  for (const key of Object.keys(publicEnv).sort()) {
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(publicEnv[key])},`);
  }

  return `\
/**
 * Auto-generated by scripts/generate-environment.ts — do not edit.
 * Mode: ${production ? 'production' : 'development'}
 *
 * Includes the production flag and CSDK_PUBLIC_* keys (browser-safe).
 * NODE_ENV and other server values come from process.env at runtime (see load-env.ts + defineConfig).
 */
export const environment = {
${lines.join('\n')}
};
`;
}

function parseMode(): 'dev' | 'prod' {
  const args = process.argv.slice(2);
  if (args.includes('--dev')) return 'dev';
  if (args.includes('--prod')) return 'prod';
  console.error('Usage: tsx scripts/generate-environment.ts --dev | --prod');
  process.exit(1);
}

function main(): void {
  const mode = parseMode();
  loadEnvFiles(mode);

  const production = mode === 'prod';
  const outFile = production ? 'environment.prod.ts' : 'environment.dev.ts';
  const outPath = resolve(angularEnvDir, outFile);
  writeFileSync(outPath, serialize(production), 'utf8');
  console.log(`[content-sdk:prebuild] Wrote ${outFile} (mode=${mode})`);
}

main();
