---
ID: "9c2af26c-21d6-4fed-a776-25a10203858e"
Parent: "e403aaf8-a18e-49fa-b448-46df8740dec9"
Template: "e403aaf8-a18e-49fa-b448-46df8740dec9"
Path: "/sitecore/templates/Project/angular-starter/LessonBooking/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260915T140356Z
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\xtGHiXAezuWnoKk27zhXOQPI5ivHTK6g
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6e084aab-de92-40b1-a72c-284b1e0e28b5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\xtGHiXAezuWnoKk27zhXOQPI5ivHTK6g
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260915T140356Z
