---
ID: "ef66ad4a-2e98-40f1-b303-cdea60660c29"
Parent: "f6715188-b4e9-408c-ad72-a0ae85e215ec"
Template: "f6715188-b4e9-408c-ad72-a0ae85e215ec"
Path: "/sitecore/templates/Project/round-rock-sasquatch-sites/Product Grid/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260511T204308Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\superuser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1f823998-7b0c-4232-b87d-2f6f7005ea50"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260511T204308Z
